services:
  # 1. BASE DE DATOS
  db:
    image: postgres:15
    container_name: hospital_db
    environment:
      - POSTGRES_DB=bd_hospital
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Útil para ver la BD desde DBeaver/PgAdmin 

  # 2. API DE OPTIMIZACIÓN
  optimizer:
    build: ./optimization_engine
    container_name: hospital_optimizer
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 # Ajustá esto según cómo corra tu API hoy
    ports:
      - "8000:8000"
    volumes:
      - ./optimization_engine:/app
    depends_on:
      - db

  # 3. LA APP WEB (Django)
  web:
    build: ./web_app
    container_name: hospital_web
    command: >
            sh -c "python manage.py migrate &&
            python manage.py init_local_data &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web_app:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
      - optimizer
    environment:
    - DB_HOST=db
    - DB_NAME=bd_hospital     
    - DB_USER=admin            
    - DB_PASS=admin          
    - API_OPTIMIZER_URL=http://optimizer:8000
    

volumes:
  postgres_data:  